//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUD_Api.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class StaffMicroservicesDB
    {
        [Key]
        [DatabaseGeneratedAttribute(DatabaseGeneratedOption.Identity)]
        public long ID { get; set; }


        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string OtherName { get; set; }
        public long StaffID { get; set; }
        public string Email { get; set; }
        public long PhoneNumber { get; set; }
        public string Address { get; set; }
        public string AccountNumber { get; set; }
        public long BankID { get; set; }
        public string BVNNo { get; set; }
        public string AccountName { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<System.DateTime> DateOfEmploymentTermination { get; set; }
        public Nullable<long> PayGroupID { get; set; }
        public int Status { get; set; }
    
        //public virtual StaffMicroservicesDB StaffMicroservicesDB1 { get; set; }
        //public virtual StaffMicroservicesDB StaffMicroservicesDB2 { get; set; }
    }
}
